import re
import datetime
from itertools import chain

wildcard_constraints:
    chr = "chr[0-9XY]{1,2}"

max_time = 12*60

def get_mem_mb(wildcards, threads):
    return threads * 3420

def get_permute_time(wildcards, threads):
    return min(max_time, int(0.3*int(wildcards.draws)/int(threads)))

include: "rules/1000g_reference.smk"
include: "rules/ukbb.smk"
include: "rules/gps/gps.smk"
include: "rules/hoeffdings.smk"
include: "rules/simgwas/simgwas.smk"
include: "rules/simgwas/simgwas_randomised.smk"
include: "rules/ldsc/ldsc.smk"
include: "rules/ldsc/ldsc_randomised.smk"
include: "rules/gps/gps_for_randomised_simgwas.smk"
include: "rules/simgwas/simgwas_experiments.smk"
include: "rules/sumher/sumher.smk"
include: "rules/sumher/ukbb_sumher.smk"
include: "rules/export.smk"
