import re
import datetime
import pandas as pd
from itertools import chain

configfile: "config.yaml"

wildcard_constraints:
    chr = "chr[0-9XY]{1,2}"

max_time = 12*60

def get_mem_mb(wildcards, threads):
    return threads * 3420

def get_permute_time(wildcards, threads, attempt):
    return min(max_time, attempt*int(0.45*int(wildcards.draws)/int(threads)))

scattergather:
    split_block_files_for_pair = 12

block_daf = pd.read_csv("resources/ldetect/available_blocks.tsv", sep = "\t")

block_daf = block_daf.query('available == True')

include: "rules/1000g_reference.smk"
include: "rules/ukbb.smk"
include: "rules/gps/gps.smk"
include: "rules/hoeffdings.smk"
include: "rules/simgwas/simgwas.smk"
include: "rules/simgwas/simgwas_randomised.smk"
include: "rules/ldsc/ldsc.smk"
include: "rules/ldsc/ldsc_randomised.smk"
include: "rules/gps/gps_for_randomised_simgwas.smk"
include: "rules/simgwas/simgwas_experiments.smk"
include: "rules/sumher/sumher.smk"
include: "rules/sumher/ukbb_sumher.smk"
include: "rules/export_ukbb.smk"
