cluster: "mkdir -p logs/{name} &&
  sbatch
  -J {name}
  -o logs/{name}/%j.out
  -e logs/{name}/%j.err
  --export ALL,OMP_NUM_THREADS={threads}
  --account MRC-BSU-SL2-CPU 
  --time {resources.runtime}
  --nodes 1
  --ntasks 1
  --cpus-per-task {threads}
  --mail-type FAIL
  --partition cclake,cclake-himem,skylake-himem,skylake,icelake,icelake-himem"
jobs: 1000
local-cores: 2
cores: 10
keep-going: True
use-conda: True
scheduler: greedy
default-resources:
  - runtime=5
  - mem_mb=3420
  - tmpdir='tmp'
set-threads:
  - merge_randomised_simulated_sum_stats=1
  - prune_merged_randomised_simulated_sum_stats=1
  - process_combined_simgwas_sum_stats=1
set-resources:
  - merge_randomised_simulated_sum_stats:
      - runtime=25
  - prune_merged_randomised_simulated_sum_stats:
      - runtime=25
  - process_combined_simgwas_sum_stats:
      - runtime=25
group-components:
  - simulate=400
  - process_randomised_simgwas=1
  - permute=1
  - ldsc_hoeffding_sumher_gps_sans_permutation=16
rerun-incomplete: True
dry-run: False
verbose: True
# TODO cluster-cancel doesn't work
cluster-cancel: scancel
